---
title: "Inferential Statistics: Estimation"
output: html_notebook
---

Inferential statistics involves two major componenets - Estimation and Hypothesis Testing. This notebook will cover 'Estimation'. 

#### Revisiting Sampling theory

Before starting with Estimation, we need to understand the sampling theory, a part of which we've also covered in the first module.

It is necessary to understand what we're drawing inferences from (*sample*) and what we're drawing inferences about (*population*).
As we've previously discussed, **Population** refers to the set of all possible people, or all possible observations, that you want to draw conclusions about, and is generally much bigger than the sample.

If I am a cognitive scientist who wants to stude=y about the brain, what should I count as my population of interest:
- All undergraduate students in Psychology at IITK?
- All students at IITK?
- Any human in the world?
- Any intelligent being in the universe?

Do we know about our population of interest?

**Random Sample**
A procedure in which every member of the population has the same chance of being selected is called a simple random sample. We can say a process has an element of randomness whenever it is possible to repeat the process and get different answers each time.

If we can’t observe the same thing twice, the observations are said to have been sampled **without replacement**, else it is called sample **with replacement**.

Also recall the defiirent kind of **biases** that can occur during sampling.

**Types of sampling**

  - *Stratified sampling*: Suppose your population is (or can be) divided into several different subpopulations, or _strata_. For eg. you’re running a study at several different sites. Instead of trying to sample randomly from the population as a whole, you instead try to collect a separate random sample from each of the strata. An example would be two equally sample people from schizophrenic and non-schizophrenic populations while studying about schizophrenia. This is also referred to as _oversampling_ because it makes a deliberate attempt to over-represent rare groups.
  - *Snowball sampling*: It is especially useful when sampling from a “hidden” or hard to access population. For instance, suppose the researchers want to conduct an opinion poll among transgender people. For first round, they'll contact the people they know, for second one they'll get contacts of other people from the first set of participants and so on. Despite the advantage that we can get data in situations that might otherwise be impossible to get any, it makes the sample highly non-random and might also be unethical if not handled properly. This is because social networks are complex things, and just because we can use them to get data doesn’t always mean we should.
  - *Convenience sampling*: The samples are chosen in a way that is convenient to the researcher, and not selected at random from the population of interest. Eg. Snowball sampling or when undergraduates or all students if an institute are recruited for a study. 
  
  Can you think of other examples of convenience sampling in biology or psychology?
  
But are such sampling methods or biases wrong?

A bias in your sampling method is only a problem if it causes you to draw the wrong conclusions. We probably need it to be random only with respect to the psychologically/biologically-relevant phenomenon of interest.
